//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Assets.Scripts
{
	[RequireComponent(typeof(AudioSource))]
		public class MusicManager : MonoBehaviour
		{
			public bool startAudioSourceOnLevelLoaded;
			static AudioClip currentlyPlaying;

			void OnLevelLoaded(int index)
			{
				if (startAudioSourceOnLevelLoaded &&currentlyPlaying != null)
				{
					audio.Play();
					currentlyPlaying = audio.clip;
				}
			}
		}
}

